# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required 
dist: trusty 
services:
  - docker
language: generic 
compiler:
  - gcc
notifications:
  email:
    recipients:
      - gm130s@gmail.com
      - jwhitley@autonomoustuff.com
env:
  matrix:
    - ROS_DISTRO="indigo" ROS_REPO=ros DOCKER_BASE_IMAGE=ros:indigo-robot
    - ROS_DISTRO="kinetic" ROS_REPO=ros DOCKER_BASE_IMAGE=ros:kinetic-robot
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed DOCKER_BASE_IMAGE=ros:kinetic-robot
    - ROS_DISTRO="lunar" ROS_REPO=ros DOCKER_BASE_IMAGE=ros:lunar-robot
    - ROS_DISTRO="melodic" ROS_REPO=ros DOCKER_BASE_IMAGE=ros:melodic-robot
    - ROS_DISTRO="melodic" ROS_REPO=ros-shadow-fixed DOCKER_BASE_IMAGE=ros:melodic-robot

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
